# Generated by Django 4.0.5 on 2023-01-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0004_alter_employee_dept_alter_employee_role_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
